[consensus_overlord]
network_port = 50000
consensus_port = 50001
controller_port = 50004
enable_metrics = true
metrics_port = 60001
domain = "test-chain-node1"

[consensus_overlord.log_config]
max_level = "info"
filter = "info"
# rolling_file_path = "./logs"
service_name = "consensus"
# agent_endpoint = "127.0.0.1:6831"
