[package]
name = "consensus"
version = "6.6.5"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
overlord = "0.4"
clap = { version = "4.2", features = ["derive"] }
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.27", features = ["full"] }
toml = "0.7"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
bytes = { version = "1.4", features = ["serde"] }
async-trait = "0.1"
ophelia = "0.3"
ophelia-blst = "0.3"
ophelia-secp256k1 = "0.3"
hex = "0.4"
derive_more = "0.99"
creep = "0.2" # match with overlord
libsm = "0.5"
rlp = "0.5"
tower = "0.4"
tracing = "0.1"

cloud-util = { package = "cloud-util", git = "https://github.com/cita-cloud/cloud-common-rs" }
cita_cloud_proto = { package = "cita_cloud_proto", git = "https://github.com/cita-cloud/cloud-common-rs" }

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
