[package]
name = "consensus"
version = "6.6.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
overlord = "0.4"
clap = { version = "3.2", features = ["derive"] }
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.20", features = ["full"] }
toml = "0.5"
log4rs = { version = "1.1", features = ["gzip"] }
backtrace = "0.3"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
bytes = { version = "1.2", features = ["serde"] }
async-trait = "0.1"

cloud-util = "0.4.1"
cita_cloud_proto = "6.6.0"
status_code = { package = "cloud-code", version = "0.4.0" }

ophelia = "0.3"
ophelia-blst = "0.3"
ophelia-secp256k1 = "0.3"
hex = "0.4"
derive_more = "0.99"
creep = "0.2"
libsm = "0.5"
rlp = "0.5"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
