[package]
name = "consensus"
version = "6.4.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
overlord = "0.3"
clap = { version = "3.1", features = ["derive"] }
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.17", features = ["full"] }
toml = "0.5"
log4rs = { version = "1.0", features = ["gzip"] }
backtrace = "0.3"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
parking_lot = "0.12"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util.git" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto.git" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code.git" }




bincode = "1.3"



cita-types = "0.1"
time = "0.1"
lru-cache = "0.1"
min-max-heap = "1.2"
hex = "0.4"


[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
