[package]
name = "consensus"
version = "6.6.2"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
overlord = "0.4"
clap = { version = "4.0", features = ["derive"] }
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.21", features = ["full"] }
toml = "0.5"
log4rs = { version = "1.2", features = ["gzip"] }
backtrace = "0.3"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
bytes = { version = "1.2", features = ["serde"] }
async-trait = "0.1"
ophelia = "0.3"
ophelia-blst = "0.3"
ophelia-secp256k1 = "0.3"
hex = "0.4"
derive_more = "0.99"
creep = "0.2" # match with overlord
libsm = "0.5"
rlp = "0.5"
tower = "0.4"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util.git", branch = "v0.6.0" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto.git", branch = "v6.6.2" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code.git", branch = "v0.6.0" }

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
